Switch from sprintf to snprintf. sprintf is deprecated.
theos/logos pull request #88
Opened 2022-09-21 08:26 UTC by HearseDev

What does this implement/fix? Explain your changes.
---------------------------------------------------
sprintf is deprecated, use of snprintf instead to avoid warnings.

Does this close any currently open issues?
------------------------------------------
…

Any relevant logs, error output, etc?
-------------------------------------

Any other comments?
-------------------
…

Where has this been tested?
---------------------------
**Operating System:** …

**Platform:** …

**Target Platform:** …

**Toolchain Version:** …

**SDK Version:** …

2022-10-28 21:27 UTC, uroboro commented on bin/lib/Logos/Generator/Base/Property.pm
> +		$build .= " snprintf(_typeEncoding, _nBytes,\"%s\@:\", \@encode($propertyType));";
One quick request and we should be good to go, sorry for the delay

```suggestion
		$build .= " snprintf(_typeEncoding, _nBytes, \"%s\@:\", \@encode($propertyType));";
```

2022-10-28 21:27 UTC, uroboro requested changes
One quick request and we should be good to go, sorry for the delay

2022-10-29 00:35 UTC, PoomSmart approved these changes

2022-10-29 22:30 UTC, uroboro approved these changes

2022-10-29 22:31 UTC, merged